# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "release-note/infra"
    assignees:
      - "OrlinVasilev"
    reviewers:
      - "OrlinVasilev"

  # - package-ecosystem: "gomod"
  #   directory: "/src"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "release-note/update"
  #   ignore:
  #     - dependency-name: "gopkg.in/h2non/gock.v1"
  #     - dependency-name: "github.com/goharbor/harbor/src/server/v2.0/restapi/operations/user"
  #     - dependency-name: "github.com/theupdateframework/notary"
  #     - dependency-name: "github.com/go-openapi/runtime"

  # More will be needed