name: ManualDependabot

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Generate API
      run: |
        make gen_apis
        pwd=$(pwd)
        echo "DIRECTORY_PATH=$(echo $pwd/src)" >> $GITHUB_ENV
    - name: Checkout dependabot
      run: |
        cd /tmp/
        git clone https://github.com/dependabot/dependabot-script
    - name: Build image
      run: |
        cd /tmp/dependabot-script
        docker build -t "dependabot/dependabot-script" -f Dockerfile .
    - name: Run dependabot
      env:
        # Select your package manager
        PACKAGE_MANAGER: go_modules
        DIRECTORY_PATH: /src
        OPTIONS: |
           { "tidy": true, "vendor": true, "labeler": "release-note/ignore-for-release" }
        GITHUB_ACCESS_TOKEN: ${{ github.token }}
      run: |
        echo $PWD
        ls
        docker run -v $PWD:/harbor -e PROJECT_PATH=$GITHUB_REPOSITORY -e PACKAGE_MANAGER=$PACKAGE_MANAGER -e DIRECTORY_PATH=$DIRECTORY_PATH -e DIRECTORY=harbor -e GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN -e OPTIONS="$OPTIONS" dependabot/dependabot-script
